### ISSUE TITLE
Screenshot is cut off

### ISSUE THREAD

**Issue by okravchuk** [tsayen/dom-to-image#107]
Hello,
I have such dashboard:
![image](https://cloud.githubusercontent.com/assets/19709467/23948827/7b599818-098d-11e7-84cd-578597fc94b0.png)

However if I use 
            var node = $('.renderer-container')[0];
            domtoimage.toPng(node)
                .then(function (dataUrl) {
                    var img = new Image();
                    img.src = dataUrl;
                    node.appendChild(img);
                })
                .catch(function (error) {
                    console.error('oops, something went wrong!', error);
                });
screenshot includes only visible part of dashboard in browser (side available with scrolling is hidden):
![image](https://cloud.githubusercontent.com/assets/19709467/23948760/2482e22e-098d-11e7-9aec-2ecf3e9bbcd9.png)

Is there any way (mode) of using your library to capture whole node?

**Comment by tsayen** [comment]
make sure youre selecting the correct node

**Comment by tsayen** [comment]
please use the issue template next time

**Comment by okravchuk** [comment]
yes, my selection is correct - node is a container for all the items.

**Comment by tsayen** [comment]
I think you're selecting too high in the hierarchy. If you think Im wrong,
please provide a jsfiddle

On Mar 15, 2017 14:22, "okravchuk" <notifications@github.com> wrote:

yes, my selection is correct - node is a container for all the items.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/tsayen/dom-to-image/issues/107#issuecomment-286739034>,
or mute the thread
