### ISSUE TITLE
overflow-y:scroll is not support ; hidden content is not shown 

### ISSUE THREAD

**Issue by danmaidesenling** [tsayen/dom-to-image#176]
$(function () {
		$("#downloadPdf").click(function(){
			domtoimage.toBlob(document.getElementById('pdfContainer'))
				.then(function (blob) {
					window.saveAs(blob, 'my-node.png');
				});
		});
    });
![555](https://user-images.githubusercontent.com/7588416/34032057-4b60bde4-e1af-11e7-92e0-8baf2f03c07f.png)
![666](https://user-images.githubusercontent.com/7588416/34032058-4c567428-e1af-11e7-837b-1a59ef00ebf1.png)

**Comment by Mahmuduman** [comment]
Hi i have same Problem with scroll rendering,
How can i fix This ?

Thanks for ansvers..

**Comment by Mahmuduman** [comment]
#element{
overflow:scroll;
}

i want render to full scroled area

**Comment by JoolsCaesar** [comment]
That appears to be working perfectly. The point of dom-to-image is to get an accurate representation of the DOM. If you hid content with overflow styling and it ignored that fact and showed it anyway, **that** would be a bug. If you want an image of the content rather than the scrollable container, you'll need to call it on the content element(s)
E.g.
```
<div id="pdfContainer">
   <span id="pdfContainerContent">
      ....
   </span>
</div>
```

`domtoimage.toBlob(document.getElementById('pdfContainerContent'))`

**Comment by danmaidesenling** [comment]
get it . thanks ,bro
