### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [tsayen/dom-to-image#278]
Hi, what is the current status of this project? Is it still maintained?

So far I see no progress since https://github.com/tsayen/dom-to-image/issues/187

**Comment by IDisposable** [comment]
I have a fork/rename going and am planning on pulling some merges in...

**Comment by IDisposable** [comment]
https://github.com/1904labs/dom-to-image-more is the GitHub, the https://www.npmjs.com/package/dom-to-image-more is the package. Now entertaining suggestions for what to merge in first :)

**Comment by AdamZaczek** [comment]
@IDisposable Great! I'll give it a try

**Comment by Venryx** [comment]
Here are the alternatives to dom-to-image I've found that are still being maintained (at least somewhat):
1) https://github.com/cburgmer/rasterizeHTML.js -- It's based on the same approach as this library uses, except it's more actively maintained.
2) https://github.com/niklasvh/html2canvas -- Seems to use a different approach that is lower-level; in any case it has a lot more code files. It appeared to work fine when I used it, however only has minor updates/maintenance being made.

EDIT: @IDisposable's dom-to-image fork above is a third option:

3) https://github.com/1904labs/dom-to-image-more

And here is a fourth one: (also a fork of dom-to-image)

4) https://github.com/bubkoo/html-to-image

**Comment by IDisposable** [comment]
I also have a fork and will merge and maintain at
https://github.com/1904labs/dom-to-image-more with NPM at
https://www.npmjs.com/package/dom-to-image-more

**Comment by Venryx** [comment]
@IDisposable Okay, good to hear you'll be maintaining your fork as well. :)

**Comment by signalwerk** [comment]
@tsayen this is a great project but it's slowly dying because there is no maintainer in place. If you could give one or two active people maintainer-status to this repository this would really benefit the whole project. It's always hard to let the children walk on their own feet but I guess the community would highly appreciate it.

**Comment by DanielRuf** [comment]
> @tsayen this is a great project but it's slowly dying because there is no maintainer in place. If you could give one or two active people maintainer-status to this repository this would really benefit the whole project. It's always hard to let the children walk on their own feet but I guess the community would highly appreciate it.

The best in the longterm would be to move it to an org.

**Comment by tsayen** [comment]
Thanks for the heads up. 

I would be very hesitant to share or transfer maintainer rights to this project, as I'm aware of security risks this brings to the users. I don't completely reject the idea though.

I'm aware of the forks and I see nothing wrong with people making or using them, as long as it's compatible with the license. Looks like at least one fork at https://github.com/bubkoo/html-to-image is breaking the license terms.

Let me think about what to do with this repository. I'll get back to you guys within a month. It might be I'll find some time to clean up here.

**Comment by tsayen** [comment]
I have a question to people interested in this project going on - what is your use case/platform?
What is the biggest issue (a link to existing issue would be fine) you want fixed?

**Comment by ghost** [comment]
angular 7 / Chrome Safari,  I use this mainly for printing svg, that i embed with jspdf. Just stumble on mat-icon not rendering properly.

**Comment by ghost** [comment]
sample https://stackblitz.com/edit/angular-dom2image-j5m93p

**Comment by signalwerk** [comment]
@tsayen Thank you for your answer. Are you aware of the fact that you can setup github so that a pull-request needs some reviewers before they can get merged. Thats usually how projects like that work to avoid security-issues. If you have a PR that is reviewed from 2–3 people it gets merged. 

I completely understand that it's nice to keep the control but please consider bringing the project to a more sustainable form. 

My usecase: [carbon](https://carbon.now.sh/) uses dom-to-image and I would like to work on the font-subsetting to get smaller SVG's
