### ISSUE TITLE
CORS issue in FireFox

### ISSUE THREAD

**Issue by allenhwkim** [tsayen/dom-to-image#29]
http://plnkr.co/edit/MYEUbj?p=preview

**Comment by tsayen** [comment]
It will not work this way because the image is served from a different domain than the script. The script performs XMLHttpRequest to get the image data, and request will rather not succeed.

See request headers (pay attention to the Origin field):

```
GET /eQxoG0h.jpg HTTP/1.1
Host: i.imgur.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://run.plnkr.co/wrtWddsqSpO1Cd9b/
Origin: http://run.plnkr.co
Connection: keep-alive
```

Here is the error you get on console:

```  
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://imgur.com/eQxoG0h. (Reason: CORS header 'Access-Control-Allow-Origin' missing).  
```

So, you will not get this image rendered, as the script simply does not have access to it. I believe you're having the same problem as in issue #22

**Comment by tomgallagher** [comment]
I struggled with this for a while, I was the person who opened issue #22. The problem is that the XMLHttpRequest is very strict on the kinds of headers it wants back. The person who runs the server with the resource being denied may not be so strict (I mean you Amazon S3). The way I dealt with it was to change the original URL on the page to a 'mirror' URL that worked through a GET API on my server, where I can control the headers, and just run all the resources through that. Hope that helps.

**Comment by allenhwkim** [comment]
What I expect is if one of images has CORS issue, it's better to render without that image instead of stopping the whole operation without giving the detailed error message.

Yes "I will not get this image rendered", but how about others?

My web page may have hundreds of images with one external image link, then I still want to have the whole screen shot without the image.

**Comment by tsayen** [comment]
OK, I've missed the fact that you're actually getting an error instead result of the rendering. Another interesting thing is - this example works on Chrome, event without any CORS issues. Will take a llook at that.

**Comment by RedsaiyanAlpha** [comment]
Hello, I am having an issue with firefox 46.0.1. I am having image converted like this
**
[Uploading image.png…]
**
Can you please help? Thanks

**Comment by tsayen** [comment]
@RedsaiyanAlpha please provide a jsfiddle or something like that

**Comment by RedsaiyanAlpha** [comment]
Please check https://jsfiddle.net/w9hs8yzr/2/

**Comment by RedsaiyanAlpha** [comment]
Any Update?

**Comment by tsayen** [comment]
Sorry, currently I'm travelling, but will definitely take a look next week.

**Comment by RedsaiyanAlpha** [comment]
Thanks. Enjoy!

**Comment by tsayen** [comment]
@RedsaiyanAlpha sorry for delay. Your jsfiddle gives me an error 
```
ReferenceError: domtoimage is not defined
conversion() _display:88
1 _display:88:16
```
you might want to take a look at this example fiddle http://jsfiddle.net/tsayen/8h13tmcj/2/ on how to load and use the lib

**Comment by ekanur** [comment]
Hello, find same error when load image from different origin.
