### ISSUE TITLE
Bottom and right side of image chopped off

### ISSUE THREAD

**Issue by chughes87** [tsayen/dom-to-image#44]
https://plnkr.co/edit/f57wfo

**Comment by azain** [comment]
I facing the same issue!

**Comment by sparcut** [comment]
+1 Just playing around with this lib, found that since I had a border on the dom element that only the top+left border was being shown... Kinda annoying. :/

Picture of dom:
![191fa](https://cloud.githubusercontent.com/assets/16233822/17621759/df2ac1ae-60d8-11e6-9815-2e106f4fbf4f.png)

Picture of saved image:
![my-album-art](https://cloud.githubusercontent.com/assets/16233822/17621760/e1ba42d2-60d8-11e6-83e1-7414bf4e0123.png)


My code:

	function captureImg() {
		var ele = $("#canvas")[0];

		domtoimage.toBlob(ele)
			.then(function(blob) {
				window.saveAs(blob, "my-img.png");
			});
	}

**Comment by karthickvkumar** [comment]
Hi @tsayen, thanks for this awesome library Is there any solution for this issue? 

Thanks in advance
