### ISSUE TITLE
Use in nodejs

### ISSUE THREAD

**Issue by swampthang** [tsayen/dom-to-image#46]
Thanks so much for the awesome code! I'm building an Electron app - electron.atom.io - and need to create a series of png images of a specific div's contents, saving each frame of animation. I'm using the following script:
```
// domtoimg test
var stageContainer = document.getElementById('stage-container');
domtoimage.toPng(stageContainer)
.then(function (dataUrl) {
    fs.writeFileSync('./tmp/pngs/img'+padded+'.png', dataUrl);
})
.catch(function (error) {
    console.error('oops, something went wrong!', error);
});
```
Files are saving but I am getting files that are unreadable as PNGs. They're coming out like this..

![newimg0001](https://cloud.githubusercontent.com/assets/428757/16651815/132a7650-440c-11e6-806d-e70fefba8f4c.png)

Is this something I'm doing or a bug?

**Comment by tsayen** [comment]
Hi! I think that is a dataURL you're getting, it's binary image content, but base64-encoded. It's fine to use on a web page, like `<image src="data url goes here">`, because the browser will decode it first. I think you need `domtoimage.toBlob` method - it gives you binary blob, which you can save to a file.
