### ISSUE TITLE
toSVG doesn't actually create an SVG file

### ISSUE THREAD

**Issue by pete-hotchkiss** [tsayen/dom-to-image#64]
It would seem doing the following

```
domtoimage.toSvg(document.getElementByID('foo')
.then( (b) => {
 // save the file
});
```

when the HTML has
```
<div class="bar" id="foo">Label</div>
```

will generate an SVG file that looks like 

```
<svg xmlns="http://www.w3.org/2000/svg" width="64" height="33"><foreignObject x="0" y="0" width="100%" height="100%"><div class="button  uufcs0" id="Dom2Img-Button" xmlns="http://www.w3.org/1999/xhtml" style="...">Label</div></foreignObject></svg>
```

Now, this isn't an SVG representation of the DOM. It's just the DOM wrapped in an SVG tag - meaning it's useless and wont render anywhere else I might want to edit the create .svg file.

I'd expect it to be more like
```
<svg>
<g fill="#41b6e6" fill-opacity="1" stroke="none" font-family="Open Sans Semibold" font-size="18" font-weight="630" font-style="normal">
<text fill="#000000" fill-opacity="0.74902" stroke="none" xml:space="preserve" x="497.5" y="80" font-family="Open Sans Semibold" font-size="13" font-weight="630" font-style="normal" 
 >Label</text>
</g>
</svg>
```

i.e. an actual SVG file...

am I missing a flag here or something that generates it correctly?

**Comment by tsayen** [comment]
I think you've misunderstood the `toSvg` method. It will not convert your HTML tags to their SVG "counterparts". It creates an SVG image that will contain your HTML as `foreignObject` with all the styles inlined - so that it can be saved to `.svg` file, and if you later open it with a browser (or another SVG viewer that supports `foreignObject` correctly), it should be displayed allright. For what you want to do there are probably other tools, like maybe XSLT

**Comment by pete-hotchkiss** [comment]
Ahh ok. My bad. Didn't realise it was completely different to toPNG, which
actually - well saves a PNG.


toSVG does nothing of the sort - its essentially meaningless. It just takes
dom an wraps it in an svg tag. Which BTW doesn't actually open in a
browser. I can file a new ticket for thst if you like.


might be an idea to make your docs a bit clearer.

**Comment by tsayen** [comment]
toSvg() _does_ produce a _correct_ SVG. It doesn't do it _exactly how you
would like_, but it works correctly. I'm sorry this lib doesn't do what you
would like it to do. You might want to try to implement missing
functionality yourself.

**Comment by pete-hotchkiss** [comment]
Sorry I think your misunderstanding me.

I understand now what it does ( or rather now) - my point is it doesn't
even work as your describing. The SVG it generates doesn't render in a
browser. I just get a blank white page. Regardless of what DOM element I
point it at - even a basic h1 tag.

Or is that the intended result of the library ?

**Comment by tsayen** [comment]
I think you're doing something wrong. If you were really interested in
getting help here, I suppose you would present the code that is not working
as expected (and would also double-check the tone of you comments) - but it
doesn't look like you're looking for help. For further reference, you might
want to check the readme, or the source code. This issue is closed.

**Comment by pete-hotchkiss** [comment]
I must be.

As for being inserted in help - thats why I raised the ticket - but given
how you've addressed me ( and btw I'm replying to emails on a phone so
don't actually have offending code to hand ) in such a condescending manner
I'll consider you disinterested in trying to make your library better.

Good luck and good night

**Comment by ertugruldege** [comment]
This is a really important nuance with dom-to-image.toSvg(...): what it produces isn’t a true, standalone vector graphic — it’s essentially the HTML DOM cloned inside an SVG <foreignObject> wrapper. That means you get your DOM node inside SVG (which is useful for rasterization and screenshots), but not a clean, editable SVG with path elements that you can import into editors or reuse as a vector asset. 
[GitHub](https://github.com/tsayen/dom-to-image/issues/64)

That distinction matters because most people expect toSvg to give something like a traced SVG (e.g., real <path>, <rect>, <text>, etc.), but in reality it just wraps the DOM for canvas rendering. This is why many front-end screenshot libraries struggle with quality and editability. 
[GitHub](https://github.com/tsayen/dom-to-image?utm_source=chatgpt.com)

For workflows where you need actual SVG vector output (not just a wrapped DOM), you often need a two-step process:

Convert your DOM/raster to an intermediate format (canvas → bitmap or text).

Trace/optimize into a true, editable SVG with path data.

In my experience that’s the only way to get something that’s genuinely reusable — for icons, illustrations, or integration into design tools. There are tools focused on this kind of SVG generation and optimization (e.g., clean tracing workflows), and if people are interested in experimenting with high-quality SVG generation from DOM/raster inputs, you might find https://tosvg.com/
 helpful for prototyping and testing better conversion results.

**Comment by forever0714yuan** [comment]
你好，我已收到你的来信。辛苦了！！
