### ISSUE TITLE
[Question] Why not `node.cloneNode(true)`?

### ISSUE THREAD

**Issue by freeall** [tsayen/dom-to-image#96]
Hi,

I was wondering why, when you copy the DOM, don't just use `node.cloneNode(true)`. It makes a deep copy of the node.

I'm guessing that you know this, so I was interested to find out why this method isn't good in your case.

**Comment by tsayen** [comment]
Hi. Because I also need to process the clones, e.g. copy computed styles (`Node.cloneNode` does not do this for you, unfortunately).

**Comment by freeall** [comment]
The way I'm thinking about it in my head, a node's computed style is a mix between the matching rules from stylesheets (`document.styleSheets`) and the `style` attribute.  But when you copy a node the `style` attribute should be copied with it.

But maybe I'm missing something here?

**Comment by tsayen** [comment]
Unfortunately, this is not the way it works, you may want to play with it
yourself. Styles are not cloned.

On Feb 10, 2017 16:13, "Tobias Baunbæk Christensen" <
notifications@github.com> wrote:

The way I'm thinking about it in my head, a node's computed style is a mix
between the matching rules from stylesheets (document.styleSheets) and the
style attribute. But when you copy a node the style attribute should be
copied with it.

But maybe I'm missing something here?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tsayen/dom-to-image/issues/96#issuecomment-278970612>,
or mute the thread

**Comment by freeall** [comment]
Of course you already got it working, so no real reason to change it, but I was just interested when I saw the code. I've done some more lowlevel DOM stuff so I have an interest in it :)

I think I have a project where we'll use `dom-to-image` and maybe I'll take a look at it then.

Thanks a lot for answering!
